# Generated by Django 5.2.2 on 2026-06-04 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('uz', "O'zbekcha"), ('ru', 'Русский'), ('it', 'Italiano'), ('es', 'Español'), ('ja', '日本語')], default='en', max_length=5, verbose_name='Preferred language')),
                ('newsletter_subscribed', models.BooleanField(default=True, verbose_name='Newsletter subscribed')),
                ('saved_tours', models.ManyToManyField(blank=True, related_name='saved_by', to='tours.tour', verbose_name='Saved tours')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
    ]
