# Generated by Django 5.2.2 on 2026-06-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0002_cityimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticCity',
            fields=[
            ],
            options={
                'verbose_name': 'Shahar (Ichki Tur)',
                'verbose_name_plural': 'Shaharlar (Ichki Tur)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('destinations.city',),
        ),
    ]
