# Generated by Django 5.2.2 on 2026-06-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ichki_turlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domesticcity',
            options={'verbose_name': 'Domestic city', 'verbose_name_plural': 'Domestic cities'},
        ),
    ]
