# Generated by Django 5.2.2 on 2026-06-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('icon', models.CharField(blank=True, default='check', max_length=60, verbose_name='Tabler icon name')),
            ],
            options={
                'verbose_name': 'Hotel amenity',
                'verbose_name_plural': 'Hotel amenities',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_uz', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_it', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_es', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ja', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_it', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_es', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ja', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_it', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('superior', 'Superior'), ('boutique', 'Boutique'), ('resort', 'Resort'), ('hostel', 'Hostel'), ('luxury', 'Luxury')], default='standard', max_length=20, verbose_name='Category')),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3, verbose_name='Stars')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hotels/covers/', verbose_name='Cover image')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ja', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Check-in time')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Check-out time')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price from (per night)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.city', verbose_name='City')),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.hotelamenity', verbose_name='Amenities')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel image',
                'verbose_name_plural': 'Hotel images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('suite', 'Suite'), ('family', 'Family Room'), ('deluxe', 'Deluxe'), ('presidential', 'Presidential Suite')], default='double', max_length=20, verbose_name='Room type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ja', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='Capacity (persons)')),
                ('price_per_night', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price per night')),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list', verbose_name='Amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Hotel room',
                'verbose_name_plural': 'Hotel rooms',
                'ordering': ['room_type'],
            },
        ),
    ]
