# Generated by Django 5.2.15 on 2026-07-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotelcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Views count'),
        ),
    ]
