# Generated by Django 5.2.2 on 2026-06-20 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Sequence in the itinerary: 1, 2, 3…', verbose_name='Order')),
                ('nights', models.PositiveIntegerField(default=1, help_text='Nights spent in this city', verbose_name='Nights')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_stops', to='destinations.city', verbose_name='City')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tours.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Tour stop',
                'verbose_name_plural': 'Tour stops',
                'ordering': ['order'],
                'unique_together': {('tour', 'order')},
            },
        ),
    ]
