# Generated by Django 5.2.15 on 2026-07-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_attractionimage'),
        ('tours', '0002_tourstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourday',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='tour_days', to='destinations.attraction', verbose_name='Attractions'),
        ),
    ]
