# Generated by Django 5.2.15 on 2026-07-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourday_attractions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together=set(),
        ),
    ]
