# Generated by Django 5.2.15 on 2026-07-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourday_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourday',
            unique_together={('tour', 'day_number')},
        ),
    ]
