# Generated by Django 5.2.2 on 2026-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_set_default_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('page', models.CharField(choices=[('ichki_turlar', 'Domestic Tours'), ('home', 'Home'), ('tours', 'Tours'), ('destinations', 'Destinations'), ('hotels', 'Hotels'), ('guides', 'Guides')], db_index=True, default='ichki_turlar', help_text="Which page's hero slideshow this image belongs to.", max_length=32, verbose_name='Page')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Image')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'verbose_name_plural': 'Hero slides',
                'ordering': ['page', 'order', '-created_at'],
            },
        ),
    ]
