# Generated by Django 5.2.15 on 2026-07-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_ja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt text'),
        ),
    ]
