# Generated by Django 5.2.15 on 2026-07-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heroslide_alt_en_heroslide_alt_es_heroslide_alt_it_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('site_name', models.CharField(default='UNITUR', max_length=200, verbose_name='Site name')),
                ('site_tagline', models.CharField(blank=True, max_length=500, verbose_name='Tagline')),
                ('site_tagline_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_tagline_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_tagline_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_tagline_it', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_tagline_es', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_tagline_ja', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tagline')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('phone_secondary', models.CharField(blank=True, max_length=30, verbose_name='Secondary phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, verbose_name='Secondary email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_uz', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_it', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_es', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_ja', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Working hours')),
                ('working_hours_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('working_hours_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('working_hours_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('working_hours_it', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('working_hours_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('working_hours_ja', models.CharField(blank=True, max_length=200, null=True, verbose_name='Working hours')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Format: +998901234567', max_length=30, verbose_name='WhatsApp number')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords', verbose_name='Meta keywords')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer text')),
                ('footer_text_en', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('footer_text_uz', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('footer_text_ru', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('footer_text_it', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('footer_text_es', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('footer_text_ja', models.TextField(blank=True, null=True, verbose_name='Footer text')),
                ('copyright_text', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, verbose_name='Copyright text')),
                ('copyright_text_en', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
                ('copyright_text_uz', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
                ('copyright_text_ru', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
                ('copyright_text_it', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
                ('copyright_text_es', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
                ('copyright_text_ja', models.CharField(blank=True, default='© 2024 UNITUR. All rights reserved.', max_length=200, null=True, verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
