# Generated by Django 5.2.15 on 2026-07-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='page',
            field=models.CharField(choices=[('ichki_turlar', 'Domestic Tours'), ('home', 'Home'), ('tours', 'Tours'), ('destinations', 'Destinations'), ('hotels', 'Hotels'), ('guides', 'Guides'), ('faq', 'FAQ')], db_index=True, default='ichki_turlar', help_text="Which page's hero slideshow this image belongs to.", max_length=32, verbose_name='Page'),
        ),
    ]
