# Generated by Django 5.2.2 on 2026-06-20 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'City image',
                'verbose_name_plural': 'City images',
                'ordering': ['order'],
            },
        ),
    ]
