# Generated by Django 5.2.15 on 2026-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_cityimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='caption_es',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='caption_it',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='caption_ja',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='caption_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='caption_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_ja',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cityimage',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
