# Generated by Django 5.2.15 on 2026-07-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_cityimage_caption_en_cityimage_caption_es_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attractions/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('caption_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_it', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('caption_ja', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='destinations.attraction', verbose_name='Attraction')),
            ],
            options={
                'verbose_name': 'Attraction image',
                'verbose_name_plural': 'Attraction images',
                'ordering': ['order'],
            },
        ),
    ]
