# Generated by Django 5.2.2 on 2026-06-04 17:05

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_it', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, default='book', max_length=60, verbose_name='Tabler icon name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ja', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Guide category',
                'verbose_name_plural': 'Guide categories',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('name_it', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('name_ja', models.CharField(max_length=80, null=True, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_uz', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_it', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_es', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_title_ja', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_uz', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_it', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_es', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('seo_description_ja', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_it', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ja', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='Cover image')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_uz', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_it', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_es', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('excerpt_ja', models.TextField(blank=True, max_length=500, null=True, verbose_name='Excerpt')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_uz', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_it', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_es', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('content_ja', ckeditor.fields.RichTextField(null=True, verbose_name='Content')),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Reading time (min)')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Views count')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='guides.guidecategory', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='guides.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
