# Generated by Django 5.2.15 on 2026-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive articles are hidden from the site', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured article appears at the top', verbose_name='Featured'),
        ),
    ]
