# Generated by Django 5.2.15 on 2026-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_article_is_active_alter_article_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Likes count'),
        ),
    ]
