# Generated by Django 5.2.15 on 2026-07-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_article_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes_count',
        ),
    ]
