# Generated by Django 5.2.2 on 2026-06-04 17:05

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('inquiry_type', models.CharField(choices=[('tour', 'Tour Booking'), ('hotel', 'Hotel Booking'), ('corporate', 'Corporate / MICE'), ('custom', 'Custom Trip')], default='tour', max_length=20, verbose_name='Inquiry type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='submitted', max_length=20, verbose_name='Status')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Country of origin')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Preferred travel date')),
                ('num_adults', models.PositiveSmallIntegerField(default=2, verbose_name='Number of adults')),
                ('num_children', models.PositiveSmallIntegerField(default=0, verbose_name='Number of children')),
                ('special_requests', models.TextField(blank=True, verbose_name='Special requests')),
                ('budget_range', models.CharField(blank=True, choices=[('economy', 'Economy (< $500)'), ('standard', 'Standard ($500 – $1,500)'), ('premium', 'Premium ($1,500 – $3,000)'), ('luxury', 'Luxury (> $3,000)')], max_length=20, verbose_name='Budget range')),
                ('source', models.CharField(choices=[('web', 'Website'), ('email', 'Email'), ('phone', 'Phone'), ('social', 'Social Media'), ('referral', 'Referral')], default='web', max_length=20, verbose_name='Source')),
                ('notes', models.TextField(blank=True, help_text='Visible to staff only', verbose_name='Internal notes')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Created from IP')),
                ('confirmation_number', models.CharField(default=apps.bookings.models._generate_confirmation_number, editable=False, max_length=10, unique=True, verbose_name='Confirmation number')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tours.tourdeparture', verbose_name='Tour departure')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='hotels.hotel', verbose_name='Hotel')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tours.tour', verbose_name='Tour')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
