# Generated by Django 5.2.15 on 2026-07-03 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_inquiry_email_alter_inquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–20 digits, +, spaces, - or () allowed).', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Phone'),
        ),
    ]
