# Generated by Django 5.2.15 on 2026-07-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_inquiry_phone'),
        ('tours', '0006_alter_tourday_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tours.tourcategory', verbose_name='Tour category'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='custom_category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom category'),
        ),
    ]
