# Generated by Django 5.2.2 on 2026-06-04 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('review_type', models.CharField(choices=[('tour', 'Tour Review'), ('hotel', 'Hotel Review'), ('general', 'General Review')], default='general', max_length=10, verbose_name='Review type')),
                ('guest_name', models.CharField(blank=True, max_length=100, verbose_name='Guest name')),
                ('guest_country', models.CharField(blank=True, max_length=100, verbose_name='Guest country')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('title', models.CharField(max_length=200, verbose_name='Review title')),
                ('body', models.TextField(verbose_name='Review body')),
                ('travel_date', models.DateField(blank=True, null=True, verbose_name='Travel date')),
                ('status', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('is_verified', models.BooleanField(default=False, help_text='Set by staff for confirmed bookings', verbose_name='Verified purchase')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Helpful votes')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotels.hotel', verbose_name='Hotel')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour', verbose_name='Tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Registered user')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
