# Generated by Django 5.2.15 on 2026-07-30 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Admin replied at'),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, verbose_name='Admin reply'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display in home page testimonials', verbose_name='Is featured on home page'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('image', models.ImageField(upload_to='reviews/photos/', verbose_name='Photo')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Review')),
            ],
            options={
                'verbose_name': 'Review image',
                'verbose_name_plural': 'Review images',
            },
        ),
    ]
